name: deploy
on:
  repository_dispatch:
    types: [deploy-service]
    
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: sh deploy-app.sh {{ github.event.client_payload.environment }} {{ github.event.client_payload.branch }}
        